// ─── BlissOven Product Database ─────────────────────────────────────────────

export type WeightOption = {
  label: string;
  price: string;
};

export type CustomisableOption = {
  name: string;
  choices: string[];
};

export interface Product {
  id: string;
  category: string;
  subcategory: string;
  name: string;
  slug: string;
  description: string;
  price: string;
  image: string;
  isAvailable: boolean;
  inStock: boolean;
  isFeatured: boolean;
  isSeasonal: boolean;
  isBestseller: boolean;
  isActive: boolean;
  prepTime: string;
  isEggless: boolean;
  egglessAvailable: boolean;
  isCustomisable: boolean;
  customisableOptions: CustomisableOption[];
  weightOptions: WeightOption[];
  badge?: string;
  flavorProfile?: string;
  gradient?: string;
}

export const products: Product[] = [
  // ─── BAKED CAKES ──────────────────────────────────────────────────────────
  {
    id: "bc-001",
    category: "Baked Cakes",
    subcategory: "Classic",
    name: "Fruit Cake",
    slug: "fruit-cake",
    description: "A timeless classic layered with seasonal fruits and fresh cream — light, moist, and full of natural sweetness.",
    price: "₹XXX",
    image: "/products/baked-cakes/fruit-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    flavorProfile: "Fresh & Fruity",
    gradient: "from-rose-100 to-orange-50",
  },
  {
    id: "bc-002",
    category: "Baked Cakes",
    subcategory: "Classic",
    name: "Chocolate Cake",
    slug: "chocolate-cake",
    description: "Indulge in deep, velvety chocolate layers with silky ganache and rich cream — a chocoholic's dream.",
    price: "₹XXX",
    image: "/products/baked-cakes/chocolate-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
      { name: "Decoration", choices: ["Classic", "Premium Drip", "Floral"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    badge: "Bestseller",
    flavorProfile: "Rich & Decadent",
    gradient: "from-stone-200 to-amber-50",
  },
  {
    id: "bc-003",
    category: "Baked Cakes",
    subcategory: "Classic",
    name: "Pineapple Cake",
    slug: "pineapple-cake",
    description: "Tropical pineapple chunks folded into airy sponge with whipped cream — light, refreshing, celebration-ready.",
    price: "₹XXX",
    image: "/products/baked-cakes/pineapple-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
    ],
    flavorProfile: "Tropical & Light",
    gradient: "from-yellow-50 to-lime-50",
  },
  {
    id: "bc-004",
    category: "Baked Cakes",
    subcategory: "Classic",
    name: "Butterscotch Cake",
    slug: "butterscotch-cake",
    description: "Golden butterscotch cream over fluffy vanilla sponge, topped with crunchy caramelised praline bits.",
    price: "₹XXX",
    image: "/products/baked-cakes/butterscotch-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
    ],
    flavorProfile: "Caramel & Sweet",
    gradient: "from-amber-100 to-yellow-50",
  },
  {
    id: "bc-005",
    category: "Baked Cakes",
    subcategory: "Premium",
    name: "Red Velvet Cake",
    slug: "red-velvet-cake",
    description: "Iconic crimson layers with tangy cream cheese frosting — dramatic, romantic, and utterly irresistible.",
    price: "₹XXX",
    image: "/products/baked-cakes/red-velvet-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
      { name: "Decoration", choices: ["Classic", "Roses", "Luxury"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    badge: "Fan Favourite",
    flavorProfile: "Velvety & Tangy",
    gradient: "from-red-50 to-rose-50",
  },
  {
    id: "bc-006",
    category: "Baked Cakes",
    subcategory: "Premium",
    name: "Chocolate Truffle Cake",
    slug: "chocolate-truffle-cake",
    description: "Luxury dark chocolate truffle ganache between moist cocoa sponge layers — deeply intense, sinfully rich.",
    price: "₹XXX",
    image: "/products/baked-cakes/chocolate-truffle-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
      { name: "Decoration", choices: ["Classic Ganache", "Gold Dusted", "Berry Topped"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    badge: "Signature",
    flavorProfile: "Intense & Luxurious",
    gradient: "from-stone-200 to-stone-100",
  },
  {
    id: "bc-007",
    category: "Baked Cakes",
    subcategory: "Classic",
    name: "Strawberry Cake",
    slug: "strawberry-cake",
    description: "Freshly sliced strawberries folded into rose-pink cream over light vanilla sponge — delicate and dreamy.",
    price: "₹XXX",
    image: "/products/baked-cakes/strawberry-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
    ],
    badge: "Seasonal",
    flavorProfile: "Fresh & Floral",
    gradient: "from-pink-50 to-rose-50",
  },
  {
    id: "bc-008",
    category: "Baked Cakes",
    subcategory: "Classic",
    name: "Black Forest Cake",
    slug: "black-forest-cake",
    description: "German-inspired masterpiece with dark cocoa sponge, whipped cream, and morello cherries in every bite.",
    price: "₹XXX",
    image: "/products/baked-cakes/black-forest-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message on Cake", choices: ["Birthday", "Anniversary", "Custom Text"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    flavorProfile: "Classic & Nostalgic",
    gradient: "from-stone-100 to-red-50",
  },

  // ─── BAKED FUSION ─────────────────────────────────────────────────────────
  {
    id: "bf-001",
    category: "Baked Fusion",
    subcategory: "Indian Royal",
    name: "Rasmalai Cake",
    slug: "rasmalai-cake",
    description: "The beloved mithai reimagined — saffron-cardamom cream, rasmalai pieces, and rose petal frosting on vanilla sponge.",
    price: "₹XXX",
    image: "/products/baked-fusion/rasmalai-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "36 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message", choices: ["Birthday", "Eid Mubarak", "Anniversary", "Custom"] },
    ],
    weightOptions: [
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    badge: "Royal Fusion",
    flavorProfile: "Saffron & Cardamom",
    gradient: "from-yellow-100 to-orange-50",
  },
  {
    id: "bf-002",
    category: "Baked Fusion",
    subcategory: "Indian Royal",
    name: "Gulab Jamun Cake",
    slug: "gulab-jamun-cake",
    description: "Mini gulab jamuns nestled between rose-syrup-soaked layers with kesar cream — pure festive indulgence.",
    price: "₹XXX",
    image: "/products/baked-fusion/gulab-jamun-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "36 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message", choices: ["Diwali Special", "Birthday", "Custom"] },
    ],
    weightOptions: [
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
    ],
    badge: "Festival Special",
    flavorProfile: "Rose & Saffron",
    gradient: "from-orange-100 to-amber-50",
  },
  {
    id: "bf-003",
    category: "Baked Fusion",
    subcategory: "Indian Royal",
    name: "Mango Cake",
    slug: "mango-cake",
    description: "Alphonso mango pulp whipped into cloud-like cream, layered over moist sponge — summer's finest gift.",
    price: "₹XXX",
    image: "/products/baked-fusion/mango-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message", choices: ["Birthday", "Anniversary", "Custom"] },
    ],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
    ],
    badge: "Summer Edition",
    flavorProfile: "Tropical & Sweet",
    gradient: "from-yellow-100 to-orange-100",
  },
  {
    id: "bf-004",
    category: "Baked Fusion",
    subcategory: "Indian Royal",
    name: "Kesar Pista Cake",
    slug: "kesar-pista-cake",
    description: "Royal saffron-pistachio cream frosted over rose-flavoured sponge — a regal celebration in every slice.",
    price: "₹XXX",
    image: "/products/baked-fusion/kesar-pista-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "36 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: true,
    customisableOptions: [
      { name: "Message", choices: ["Wedding", "Birthday", "Festival", "Custom"] },
    ],
    weightOptions: [
      { label: "1 kg", price: "₹XXX" },
      { label: "1.5 kg", price: "₹XXX" },
      { label: "2 kg", price: "₹XXX" },
    ],
    badge: "Royal",
    flavorProfile: "Kesar & Pista",
    gradient: "from-green-50 to-yellow-50",
  },

  // ─── NON-BAKED ────────────────────────────────────────────────────────────
  {
    id: "nb-001",
    category: "Non-Baked",
    subcategory: "Cheesecakes",
    name: "Tiramisu Cheesecake",
    slug: "tiramisu-cheesecake",
    description: "Italian elegance — espresso-soaked ladyfingers meet silky mascarpone cheesecake, dusted with cocoa.",
    price: "₹XXX",
    image: "/products/non-baked/tiramisu-cheesecake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "48 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
    ],
    badge: "Chef's Pick",
    flavorProfile: "Coffee & Cream",
    gradient: "from-amber-50 to-stone-100",
  },
  {
    id: "nb-002",
    category: "Non-Baked",
    subcategory: "Cheesecakes",
    name: "Blueberry Cheesecake",
    slug: "blueberry-cheesecake",
    description: "Wild blueberry compote swirled into New York-style cream cheese on a buttery graham cracker base.",
    price: "₹XXX",
    image: "/products/non-baked/blueberry-cheesecake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "48 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
    ],
    flavorProfile: "Fruity & Tangy",
    gradient: "from-purple-50 to-indigo-50",
  },
  {
    id: "nb-003",
    category: "Non-Baked",
    subcategory: "Cheesecakes",
    name: "Lotus Biscoff Cheesecake",
    slug: "lotus-biscoff-cheesecake",
    description: "The internet's favourite — caramelised Biscoff cookie butter whipped into velvety cheesecake perfection.",
    price: "₹XXX",
    image: "/products/non-baked/lotus-biscoff-cheesecake",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "48 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
    ],
    badge: "Trending",
    flavorProfile: "Caramel & Spiced",
    gradient: "from-orange-50 to-amber-100",
  },
  {
    id: "nb-004",
    category: "Non-Baked",
    subcategory: "Cheesecakes",
    name: "Strawberry Cheesecake",
    slug: "strawberry-cheesecake",
    description: "Fresh strawberry coulis draped over classic cream cheese — light, bright, and impossibly smooth.",
    price: "₹XXX",
    image: "/products/non-baked/strawberry-cheesecake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "48 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "500g", price: "₹XXX" },
      { label: "1 kg", price: "₹XXX" },
    ],
    flavorProfile: "Fresh & Creamy",
    gradient: "from-pink-50 to-red-50",
  },

  // ─── COOKIES ──────────────────────────────────────────────────────────────
  {
    id: "ck-001",
    category: "Cookies",
    subcategory: "Classic",
    name: "Choco Chip Cookies",
    slug: "choco-chip-cookies",
    description: "Golden-edged, gooey-centred cookies loaded with premium Belgian chocolate chips — baked fresh daily.",
    price: "₹XXX",
    image: "/products/cookies/choco-chip-cookies",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "6 pcs", price: "₹XXX" },
      { label: "12 pcs", price: "₹XXX" },
    ],
    badge: "Daily Fresh",
    flavorProfile: "Buttery & Chocolatey",
    gradient: "from-amber-100 to-yellow-50",
  },
  {
    id: "ck-002",
    category: "Cookies",
    subcategory: "Artisan",
    name: "Banana Oatmeal Peanut Butter Cookies",
    slug: "banana-oatmeal-peanut-butter-cookies",
    description: "Wholesome and nutty — ripe banana, rolled oats, and creamy peanut butter in every chewy, satisfying bite.",
    price: "₹XXX",
    image: "/products/cookies/banana-oatmeal-peanut-butter-cookies",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "6 pcs", price: "₹XXX" },
      { label: "12 pcs", price: "₹XXX" },
    ],
    flavorProfile: "Nutty & Wholesome",
    gradient: "from-yellow-100 to-amber-50",
  },

  // ─── BROWNIES ─────────────────────────────────────────────────────────────
  {
    id: "br-001",
    category: "Brownies",
    subcategory: "Classic",
    name: "Fudgy Brownie",
    slug: "fudgy-brownie",
    description: "The OG — dense, deeply chocolatey, with a crinkle-top and molten fudge centre that pulls apart perfectly.",
    price: "₹XXX",
    image: "/products/brownies/fudgy-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    badge: "Bestseller",
    flavorProfile: "Fudgy & Intense",
    gradient: "from-stone-200 to-amber-50",
  },
  {
    id: "br-002",
    category: "Brownies",
    subcategory: "Classic",
    name: "Walnut Brownie",
    slug: "walnut-brownie",
    description: "Crunchy California walnuts folded into our signature fudge brownie — textural contrast at its finest.",
    price: "₹XXX",
    image: "/products/brownies/walnut-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    flavorProfile: "Nutty & Rich",
    gradient: "from-amber-100 to-stone-100",
  },
  {
    id: "br-003",
    category: "Brownies",
    subcategory: "Premium",
    name: "Double Chocolate Brownie",
    slug: "double-chocolate-brownie",
    description: "Twice the chocolate — dark cocoa base swirled with premium milk chocolate chips for a double-decker delight.",
    price: "₹XXX",
    image: "/products/brownies/double-chocolate-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    flavorProfile: "Double Chocolate",
    gradient: "from-stone-200 to-stone-100",
  },
  {
    id: "br-004",
    category: "Brownies",
    subcategory: "Premium",
    name: "Triple Chocolate Brownie",
    slug: "triple-chocolate-brownie",
    description: "A chocolate trifecta — dark, milk, and white chocolate combined in one irresistibly indulgent brownie.",
    price: "₹XXX",
    image: "/products/brownies/triple-chocolate-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    badge: "Premium",
    flavorProfile: "Triple Indulgence",
    gradient: "from-stone-300 to-stone-100",
  },
  {
    id: "br-005",
    category: "Brownies",
    subcategory: "Signature",
    name: "Lotus Biscoff Brownie",
    slug: "lotus-biscoff-brownie",
    description: "Swirls of caramelised Biscoff spread over our fudge brownie base — one of our most-loved signature creations.",
    price: "₹XXX",
    image: "/products/brownies/lotus-biscoff-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    badge: "Most Loved",
    flavorProfile: "Caramel & Spice",
    gradient: "from-orange-100 to-amber-50",
  },
  {
    id: "br-006",
    category: "Brownies",
    subcategory: "Signature",
    name: "Oreo Brownie",
    slug: "oreo-brownie",
    description: "Crushed Oreos pressed into rich chocolate batter — creamy, crunchy, and deeply satisfying.",
    price: "₹XXX",
    image: "/products/brownies/oreo-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    flavorProfile: "Cookies & Cream",
    gradient: "from-slate-100 to-stone-100",
  },
  {
    id: "br-007",
    category: "Brownies",
    subcategory: "Signature",
    name: "KitKat Brownie",
    slug: "kitkat-brownie",
    description: "Crispy KitKat wafer fingers embedded in smooth dark chocolate brownie — a snap of indulgence.",
    price: "₹XXX",
    image: "/products/brownies/kitkat-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    flavorProfile: "Crispy & Chocolatey",
    gradient: "from-red-50 to-amber-50",
  },
  {
    id: "br-008",
    category: "Brownies",
    subcategory: "Classic",
    name: "Chocochips Brownie",
    slug: "chocochips-brownie",
    description: "Generously studded with Belgian chocolate chips — a celebration of chocolate in every single bite.",
    price: "₹XXX",
    image: "/products/brownies/chocochips-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    flavorProfile: "Chocolatey",
    gradient: "from-amber-50 to-stone-100",
  },
  {
    id: "br-009",
    category: "Brownies",
    subcategory: "Signature",
    name: "Nutella Brownie",
    slug: "nutella-brownie",
    description: "A Nutella core hidden inside our fudge brownie — molten, hazelnut-rich, and absolutely addictive.",
    price: "₹XXX",
    image: "/products/brownies/nutella-brownie",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: false,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "1 pc", price: "₹XXX" },
      { label: "4 pcs", price: "₹XXX" },
      { label: "8 pcs", price: "₹XXX" },
    ],
    badge: "Top Seller",
    flavorProfile: "Hazelnut & Chocolate",
    gradient: "from-amber-100 to-orange-50",
  },

  // ─── TEA TIME MUNCHIES ────────────────────────────────────────────────────
  {
    id: "tt-001",
    category: "Tea Time Munchies",
    subcategory: "Loaf Cakes",
    name: "Marble Cake",
    slug: "marble-cake",
    description: "Swirls of vanilla and chocolate in perfect harmony — a nostalgic everyday indulgence with your afternoon chai.",
    price: "₹XXX",
    image: "/products/tea-time-munchies/marble-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "400g", price: "₹XXX" },
      { label: "700g", price: "₹XXX" },
    ],
    flavorProfile: "Vanilla & Chocolate",
    gradient: "from-stone-100 to-yellow-50",
  },
  {
    id: "tt-002",
    category: "Tea Time Munchies",
    subcategory: "Loaf Cakes",
    name: "Dry Fruits Cake",
    slug: "dry-fruits-cake",
    description: "Premium raisins, cashews, and almonds in a buttery rum-soaked sponge — festive, hearty, and gifting-perfect.",
    price: "₹XXX",
    image: "/products/tea-time-munchies/dry-fruits-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "400g", price: "₹XXX" },
      { label: "700g", price: "₹XXX" },
    ],
    badge: "Gift Ready",
    flavorProfile: "Nutty & Warm",
    gradient: "from-amber-100 to-orange-50",
  },
  {
    id: "tt-003",
    category: "Tea Time Munchies",
    subcategory: "Loaf Cakes",
    name: "Britannia Style Cake",
    slug: "britannia-style-cake",
    description: "The beloved soft bite-sized treat reimagined at home — pillowy, vanilla-kissed, simple joy in every slice.",
    price: "₹XXX",
    image: "/products/tea-time-munchies/britannia-style-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "400g", price: "₹XXX" },
      { label: "700g", price: "₹XXX" },
    ],
    flavorProfile: "Light & Nostalgic",
    gradient: "from-yellow-50 to-cream",
  },
  {
    id: "tt-004",
    category: "Tea Time Munchies",
    subcategory: "Loaf Cakes",
    name: "Chocochip Cake",
    slug: "chocochip-cake",
    description: "A moist vanilla loaf cake dotted with generous chocolate chips — the perfect companion to your evening tea.",
    price: "₹XXX",
    image: "/products/tea-time-munchies/chocochip-cake",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "12 hours",
    isEggless: false,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "400g", price: "₹XXX" },
      { label: "700g", price: "₹XXX" },
    ],
    flavorProfile: "Chocolate & Vanilla",
    gradient: "from-amber-50 to-yellow-50",
  },

  // ─── DARK CHOCOLATES ──────────────────────────────────────────────────────
  {
    id: "dc-001",
    category: "Dark Chocolates",
    subcategory: "Bars",
    name: "Dry Fruit Dark Chocolate",
    slug: "dry-fruit-dark-chocolate",
    description: "Single-origin dark chocolate studded with premium almonds, cashews, and cranberries — gifting at its finest.",
    price: "₹XXX",
    image: "/products/dark-chocolates/dry-fruit-dark-chocolate",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    flavorProfile: "Dark & Nutty",
    gradient: "from-stone-200 to-stone-100",
  },
  {
    id: "dc-002",
    category: "Dark Chocolates",
    subcategory: "Bars",
    name: "Fruit N Nutty Bar",
    slug: "fruit-n-nutty-bar",
    description: "Vibrant dried fruits and mixed nuts suspended in rich dark chocolate — a textural and flavourful experience.",
    price: "₹XXX",
    image: "/products/dark-chocolates/fruit-n-nutty-bar",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    flavorProfile: "Fruity & Crunchy",
    gradient: "from-stone-100 to-red-50",
  },

  // ─── WHITE CENTRE FILLED CHOCOLATES ───────────────────────────────────────
  {
    id: "wc-001",
    category: "White Centre Filled Chocolates",
    subcategory: "Filled",
    name: "Dry Fruit White Filled Chocolate",
    slug: "dry-fruit-white-filled-chocolate",
    description: "Luscious white chocolate shell with a premium dry fruit and nut centre — elegant confectionery artistry.",
    price: "₹XXX",
    image: "/products/white-centre-filled-chocolates/dry-fruit-white-filled-chocolate",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    flavorProfile: "White & Nutty",
    gradient: "from-stone-50 to-cream",
  },
  {
    id: "wc-002",
    category: "White Centre Filled Chocolates",
    subcategory: "Filled",
    name: "Fruit N Nutty White Filled Chocolate",
    slug: "fruit-n-nutty-white-filled-chocolate",
    description: "A burst of fruity and nutty goodness wrapped in smooth, creamy white chocolate — gift box-ready.",
    price: "₹XXX",
    image: "/products/white-centre-filled-chocolates/fruit-n-nutty-white-filled-chocolate",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    flavorProfile: "Fruity & White",
    gradient: "from-yellow-50 to-stone-50",
  },
  {
    id: "wc-003",
    category: "White Centre Filled Chocolates",
    subcategory: "Filled",
    name: "Paan White Filled Chocolate",
    slug: "paan-white-filled-chocolate",
    description: "An Indian twist — refreshing betel leaf paan flavour in a white chocolate shell. Unique, festive, memorable.",
    price: "₹XXX",
    image: "/products/white-centre-filled-chocolates/paan-white-filled-chocolate",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    badge: "Unique",
    flavorProfile: "Paan & White",
    gradient: "from-green-50 to-stone-50",
  },
  {
    id: "wc-004",
    category: "White Centre Filled Chocolates",
    subcategory: "Filled",
    name: "Orange White Filled Chocolate",
    slug: "orange-white-filled-chocolate",
    description: "Bright citrus orange filling in creamy white chocolate — a zesty, refreshing confectionery experience.",
    price: "₹XXX",
    image: "/products/white-centre-filled-chocolates/orange-white-filled-chocolate",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    flavorProfile: "Citrus & Cream",
    gradient: "from-orange-50 to-yellow-50",
  },
  {
    id: "wc-005",
    category: "White Centre Filled Chocolates",
    subcategory: "Filled",
    name: "Strawberry White Filled Chocolate",
    slug: "strawberry-white-filled-chocolate",
    description: "Juicy strawberry filling inside a white chocolate shell — romantically sweet, visually stunning.",
    price: "₹XXX",
    image: "/products/white-centre-filled-chocolates/strawberry-white-filled-chocolate",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: true,
    isBestseller: false,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "100g", price: "₹XXX" },
      { label: "200g", price: "₹XXX" },
    ],
    flavorProfile: "Strawberry & Cream",
    gradient: "from-pink-50 to-stone-50",
  },
  // ─── HOMEMADE BREADS ──────────────────────────────────────────────────────
  {
    id: "hb-001",
    category: "Homemade Breads",
    subcategory: "Artisanal",
    name: "Banana Bread",
    slug: "banana-bread",
    description: "Moist, rich, and fragrant banana loaf baked fresh with ripe bananas, warm cinnamon, and a crunchy walnut topping.",
    price: "₹XXX",
    image: "/products/homemade-breads/banana-bread",
    isAvailable: true,
    inStock: true,
    isFeatured: true,
    isSeasonal: false,
    isBestseller: true,
    isActive: true,
    prepTime: "24 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "400g", price: "₹XXX" },
      { label: "800g", price: "₹XXX" },
    ],
    badge: "Bestseller",
    flavorProfile: "Banana & Walnut",
    gradient: "from-amber-100 to-yellow-50",
  },
  {
    id: "hb-002",
    category: "Homemade Breads",
    subcategory: "Healthy Choice",
    name: "Gluten Free Bread",
    slug: "gluten-free-bread",
    description: "Perfectly textured, soft, and wholesome gluten-free loaf made with premium allergen-free flours. Perfect for healthy breakfast toasts.",
    price: "₹XXX",
    image: "/products/homemade-breads/gluten-free-bread",
    isAvailable: true,
    inStock: true,
    isFeatured: false,
    isSeasonal: false,
    isBestseller: false,
    isActive: true,
    prepTime: "36 hours",
    isEggless: true,
    egglessAvailable: true,
    isCustomisable: false,
    customisableOptions: [],
    weightOptions: [
      { label: "400g", price: "₹XXX" },
    ],
    badge: "Gluten-Free",
    flavorProfile: "Soft & Nutritious",
    gradient: "from-stone-100 to-yellow-50",
  },
];

// Helper functions
export const getFeaturedProducts = () => products.filter((p) => p.isFeatured && p.isActive && p.isAvailable);
export const getBestsellers = () => products.filter((p) => p.isBestseller && p.isActive && p.isAvailable);
export const getByCategory = (category: string) =>
  products.filter((p) => p.category === category && p.isActive && p.isAvailable);
export const getCategories = () => [...new Set(products.map((p) => p.category))];
export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getSeasonalProducts = () => products.filter((p) => p.isSeasonal && p.isActive && p.isAvailable);

export const CATEGORIES = [
  { name: "Baked Cakes", emoji: "🎂", description: "Celebration cakes baked with love" },
  { name: "Baked Fusion", emoji: "✨", description: "Indian royal dessert inspirations" },
  { name: "Non-Baked", emoji: "🍰", description: "European cheesecake artistry" },
  { name: "Cookies", emoji: "🍪", description: "Fresh-baked daily" },
  { name: "Brownies", emoji: "🍫", description: "Fudgy chocolate perfection" },
  { name: "Tea Time Munchies", emoji: "☕", description: "Cozy everyday indulgences" },
  { name: "Dark Chocolates", emoji: "🖤", description: "Premium confectionery" },
  { name: "White Centre Filled Chocolates", emoji: "🤍", description: "Artisan filled chocolates" },
  { name: "Homemade Breads", emoji: "🍞", description: "Artisanal freshly baked breads" },
];
